version: '3'

services:

  node:
    build: ./
    container_name: sword_health_tasks_api_node
    volumes:
      - ./:/var/www/html/project
    
  database:
    image: mysql
    hostname: docker-mysql
    container_name: sword_health_tasks_api_mysql
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sword
      MYSQL_DATABASE: sword_health_tasks_api
    volumes:
      - database_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sword_health_tasks_api_rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_node_net

volumes:
  database_data:

networks:
  rabbitmq_node_net:
    driver: bridge