version: '3'

services:

  #node:
  #  build: ./
  #  container_name: sword_health_tasks_api_node
  #  restart: "no"
  #  volumes:
  #    - ./:/var/www/html/project
    
  database:
    image: mysql
    hostname: docker-mysql
    container_name: sword_health_tasks_api_mysql
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sword
      MYSQL_DATABASE: sword_health_tasks_api
    volumes:
      - database_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # mail:
  #   image: mailhog/mailhog:latest
  #   restart: always
  #   ports:
  #     - 1025:1025
  #     - 8025:8025

volumes:
  database_data: